#!/usr/bin/env python3
"""
Read public/icons/source.png (flat 512x512 generated by Playwright),
resize to each target size, apply rounded corners, save all PWA icons.

Requires: pip install Pillow
"""

import os
from PIL import Image, ImageDraw


SOURCE = 'public/icons/source.png'

SPECS = [
    # (output_path,                          size,  radius_pct,  maskable)
    ('public/icons/icon-192.png',             192,   0.22,        False),
    ('public/icons/icon-512.png',             512,   0.22,        False),
    ('public/icons/icon-512-maskable.png',    512,   0.00,        True),
    ('public/icons/apple-touch-icon.png',     180,   0.22,        False),
    ('public/favicon.png',                     48,   0.22,        False),
]


def round_image(img: Image.Image, radius: int) -> Image.Image:
    """Apply rounded corners via RGBA mask."""
    result = img.convert('RGBA')
    mask = Image.new('L', result.size, 0)
    draw = ImageDraw.Draw(mask)
    draw.rounded_rectangle([0, 0, result.width - 1, result.height - 1], radius=radius, fill=255)
    result.putalpha(mask)
    return result


def main() -> None:
    src = Image.open(SOURCE).convert('RGBA')

    os.makedirs('public/icons', exist_ok=True)

    for path, size, radius_pct, maskable in SPECS:
        img = src.resize((size, size), Image.LANCZOS)

        if not maskable and radius_pct > 0:
            radius = round(size * radius_pct)
            img = round_image(img, radius)

        img.save(path, 'PNG')
        tag = '  maskable' if maskable else ''
        print(f'[OK] {path}  ({size}x{size}{tag})')

    print('\nAll icons generated.')


if __name__ == '__main__':
    main()
